site_name: nnfs
repo_url: https://github.com/alb202/nnfs
site_url: https://alb202.github.io/nnfs
site_description: This is a neural network from scratch
site_author: Andrew Blumenfeld
edit_uri: edit/main/docs/
repo_name: alb202/nnfs
copyright: Maintained by <a href="https://alb202.com">alb202</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["nnfs"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alb202/nnfs
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nnfs

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
